# Generated by Django 2.2 on 2023-02-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
